name: pytest
on:
  push:

jobs:
  run-test:
    runs-on: ubuntu-20.04
    steps:

      - name: checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Deps
        run: |
          cd backend
          make install

      - name: run pytest
        run: |
          cd backend
          make test

      - name: upload coverage to codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}